steps:
# Set PR status to pending while build is ongoing
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'beta',
      'functions',
      'call','gcp-cicd-set-pending',
      '--data={"commit_sha":"$COMMIT_SHA", "logUrl":"https://console.cloud.google.com/gcr/builds/$BUILD_ID"}'
  ]

# Pull app:latest image
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'eu.gcr.io/$PROJECT_ID/app:latest']

# Build main image using :latest as build cache
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '--cache-from', 'eu.gcr.io/$PROJECT_ID/app:latest',
        '-f', 'Dockerfile',
        '-t', 'eu.gcr.io/$PROJECT_ID/app:$COMMIT_SHA',
        '.'
      ]

# Run unittests
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'run',
        'eu.gcr.io/$PROJECT_ID/app:$COMMIT_SHA',
      ]

# app image is pushed to Google Container Registry
images:
- 'eu.gcr.io/$PROJECT_ID/app:$COMMIT_SHA'